geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    # path('<int:pk>/', products, name='category'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    objects = None
    name = models.TextField(verbose_name='имя категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    href = 'products_'
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE
    )
    name = models.TextField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(
        verbose_name='короткое описание',
        max_length=60,
        blank=True
    )
    description = models.TextField(verbose_name='Описание', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

geekshop/geekshop/views.py
from django.shortcuts import render

from mainapp.models import Product


def index(request):
    title = 'GeekShop'
    products = Product.objects.all()[:2]

    context = {
        'title' : title,
        'products' : products,
    }
    return render(request, 'geekshop/index.html', context)

def contacts(request):
    title = 'Контакты'
    context = {
        'title' : title,
    }
    return render(request, 'geekshop/contact.html', context)

geekshop/mainapp/views.py
from django.shortcuts import render

# Create your views here.
from mainapp.models import ProductCategory


def products(request):
    title = 'каталог'

    links_menu = [
        {'href': 'products_home', 'name': 'дом'},
        {'href': 'products_office', 'name': 'офис'},
        {'href': 'products_modern', 'name': 'модерн'},
        {'href': 'products_classic', 'name': 'классика'},
    ]


    context = {
        'title' : title,
        'links_menu' : links_menu,
    }
    return render(request, 'mainapp/products.html', context)

geekshop/geekshop/templates/geekshop/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{{title|title}}</title>
	<link rel="stylesheet" type="text/css" href="/static/geekshop/style.css">
	<link rel="stylesheet" href="/static/geekshop/fonts/font-awesome/css/font-awesome.css">
    {% block css %}
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block content %}
        {% endblock %}
        <div class="clr"></div>

	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

</body>
</html>

geekshop/geekshop/templates/geekshop/contact.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block content %}

<div class="hero">
	<div class="header clearfix">
		{% include 'geekshop/includes/main_menu.html' %}
		<a href="#" class="basket"></a>
	</div>
	<h1>наши контакты</h1>
</div>

<div class="location">
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
</div>

{% endblock %}

geekshop/geekshop/templates/geekshop/includes/main_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'main' %}" class="active">домой</a></li>
    <li><a href="{% url 'products:index' %}">продукты</a></li>
    <li><a href="{% url 'contacts' %}">контакты</a></li>
</ul>
<a href="#" class="search"></a>

geekshop/geekshop/templates/geekshop/index.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block content %}

<div class="slider">
	<div class="header clearfix">
		{% include 'geekshop/includes/main_menu.html' %}
	</div>
	<div class="text-slider">
		<h3 class="green">тенденции</h3>
		<h3 class="big"> удобные стулья</h3>
		<p>Новый уровень комфорта. Отличные характеристики.</p>
		<a href="#" class="button-order">заказать <img src="/static/geekshop/img/arrow.png" alt=""></a>
	</div>
	<div class="navi">
		<a href="#"></a><a href="#"></a><a href="#"></a>
	</div>
</div>

<div class="featured">
	<div class="featured-menu">
			<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
	</div>
	<a class="explore" href="#">показать все <img src="/static/geekshop/img/arrow.png" alt=""></a>
	<div class="clearfix">
	</div>
	<div class="tab-content">
		{% for product in products %}
		<div class="block">
			<a href="#"><img src="/media/{product.image}}{" alt="">
				<div class="text">
					<img src="/static/geekshop/img/icon-hover.png" alt="img">
					<h4>{{product.name}}</h4>
					<p>{{product.short_desc}} </p>
				</div>
			</a>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/mainapp/style.css">
{% endblock %}

{% block content %}

<div class="hero-white">
	<div class="header clearfix">
		{% include 'geekshop/includes/main_menu.html' %}
		<a href="#" class="basket"></a>
	</div>
</div>

<div class="details">
	<div class="links clearfix">

		<ul class="links-menu">
			{% for link in links_menu%}
			<li><a href="{{link.href}}" class="{% if request.resolver_match.route == link.href %} active {% endif %}">{{link.name}}</a></li>
			{% endfor %}

		</ul>
	</div>

	<div class="details-products">
		<div class="details-slider">
			<div class="slider-product">
				<img src="/static/geekshop/img/slider1.jpg">
			</div>
			<div class="slider-control">
				<div class="block">
					<a href="#"><img src="/static/geekshop/img/controll.jpg" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="/static/geekshop/img/controll1.jpg" alt="">
						<div class="text"></div>
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="/static/geekshop/img/controll2.jpg" alt="">
						<div class="text"></div>
					</a>
				</div>
			</div>
		</div>

		<div class="description">
			<h3 class="big-bold">Отличный стул</h3>
			<h3 class="red">горячее предложение</h3>
			<p class="price"> 2585.9 <span>руб</span></p>
			<a href="#" class="red-button">
				заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
			</a>
			<div class="description-text">
				<p>Расположитесь комфортно.</p>
				<p>Отличное качество материалов
				позволит вам это.</p>
				<p>Различные цвета</p>
				<p>высочайший уровень
				эргономики и прочность.</p>
			</div>
		</div>
	</div>

	<div class="related">
		<div class="title clearfix">
			<h2>Похожие продукты</h2>
			<a class="explore" href="#">показать все <img src="/static/geekshop/img/arrow.png" alt=""></a>
		</div>
		<div class="related-products clearfix">
			<div class="block">
				<a href="#"><img src="/static/geekshop/img/product-11.jpg" alt="">
					<div class="text">
						<img src="/static/geekshop/img/icon-hover.png" alt="img">
						<h4>Стул повышенного качества</h4>
						<p>Не оторваться. </p>
					</div>
				</a>
			</div>
			<div class="block">
				<a href="#"><img src="/static/geekshop/img/product-21.jpg" alt="">
					<div class="text">
						<img src="/static/geekshop/img/icon-hover.png" alt="img">
						<h4>Стул повышенного качества</h4>
						<p>Не оторваться. </p>
					</div>
				</a>
			</div>
			<div class="block">
				<a href="#"><img src="/static/geekshop/img/product-31.jpg" alt="">
					<div class="text">
						<img src="/static/geekshop/img/icon-hover.png" alt="img">
						<h4>Стул повышенного качества</h4>
						<p>Не оторваться. </p>
					</div>
				</a>
			</div>

		</div>
	</div>
</div>

{% endblock %}